name: Deploy frontend
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            set -e
            FRONTEND_PATH=${FRONTEND_PATH:-${{ secrets.FRONTEND_PATH }}}
            FRONTEND_PATH=${FRONTEND_PATH:-/var/www/vendplug-frontend}
            cd "$FRONTEND_PATH"
            git fetch --all --prune
            git reset --hard origin/main
            git clean -fd
            echo "sha=$(git rev-parse --short HEAD) date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" > __deploy.txt
            sudo nginx -t && sudo systemctl reload nginx
